version: '3.8'

services:
  train:
    build:
      context: .
    container_name: flower-model-training
    command: python3 app/model/train.py
    volumes:
      - .:/app
    restart: "no"

  api:
    build:
      context: .
    container_name: flower-api
    ports:
      - "5000:5000"
    command: python3 app/app.py
    volumes:
      - .:/app
    restart: always
