version: '3.8'

services:
  train:
    build:
      context: .
    container_name: flower-model-training
    command: python train.py

  api:
    build:
      context: .
    container_name: flower-api
    ports:
      - "5000:5000"
    command: python app.py
    depends_on:
      - train
